CFLAGS = -g -Wall
CC = gcc

np: np_playground.c
	$(CC) $(CFLAGS) -o np_playground np_playground.c

unp: unp_playground.c
	$(CC) $(CFLAGS) -o unp_playground unp_playground.c

clean:

	rm -f np_playground
	rm -f unp_playground
